fullFuzzyData_v3_2
no_name_AxiomBank

1: stageTwoFuzzyData__at_2_97
	not: 	[integral, row_1]:		left -> 4
	not: 	[integral, row_1]:		maxLevel -> 17.569133
	not: 	[integral, row_1]:		minLevel -> -21.019526
	not: 	[integral, row_1]:		right -> 5

2: stageTwoFuzzyData__at_1_200
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.114540
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.375250
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.102553
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[derivative_increase_left, row_1]:		derivIncreaseLeft -> 1
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMaxLevel -> 0.410799
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMinLevel -> 0.129394
	not: 	[derivative_increase_left, row_1]:		derivIncreaseRight -> 0
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.117537
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseLeft -> 0
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseMaxLevel -> 0.369257
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseMinLevel -> 0.096560
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseRight -> 1
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.114540
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseLeft -> 2
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMaxLevel -> 0.752016
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMinLevel -> 0.053496
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.117537
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.117537
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0

3: stageTwoFuzzyData__at_2_227
			[derivative_increase_left, row_2]:		derivIncreaseLeft -> 5
			[derivative_increase_left, row_2]:		derivIncreaseMaxLevel -> 0.294193
			[derivative_increase_left, row_2]:		derivIncreaseMinLevel -> 0.186367
			[derivative_increase_left, row_2]:		derivIncreaseRight -> 0

4: stageTwoFuzzyData__at_1_115
	not: 	[integral, row_1]:		left -> 0
	not: 	[integral, row_1]:		maxLevel -> 15.070586
	not: 	[integral, row_1]:		minLevel -> -2.141621
	not: 	[integral, row_1]:		right -> 1

5: stageTwoFuzzyData__at_2_82
			[integral, row_1]:		left -> 4
			[integral, row_1]:		maxLevel -> 19.234830
			[integral, row_1]:		minLevel -> 10.073494
			[integral, row_1]:		right -> 1

6: stageTwoFuzzyData__at_1_247
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseLeft -> 0
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseMaxLevel -> 0.369257
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseMinLevel -> 0.096560
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseRight -> 1
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.811929
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.012597
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.420200
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.114540
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[derivative_increase_left, row_1]:		derivIncreaseLeft -> 1
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMaxLevel -> 0.410799
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMinLevel -> 0.129394
	not: 	[derivative_increase_left, row_1]:		derivIncreaseRight -> 0
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.114540
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.117537
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.114540
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.420200
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.114540
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[derivative_increase_left, row_1]:		derivIncreaseLeft -> 1
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMaxLevel -> 0.410799
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMinLevel -> 0.129394
	not: 	[derivative_increase_left, row_1]:		derivIncreaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.375250
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.102553
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseMinLevel -> 0.047434
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseRight -> 2
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.117537
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.420200
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.114540
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[derivative_increase_left, row_1]:		derivIncreaseLeft -> 1
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMaxLevel -> 0.410799
	not: 	[derivative_increase_left, row_1]:		derivIncreaseMinLevel -> 0.129394
	not: 	[derivative_increase_left, row_1]:		derivIncreaseRight -> 0
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0

7: stageTwoFuzzyData__at_2_208
			[increase_left_elementary_condition, row_2]:		increaseLeft -> 5
			[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.111488
			[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.069555
			[increase_left_elementary_condition, row_2]:		increaseRight -> 0

8: stageTwoFuzzyData__at_1_202
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseLeft -> 0
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseMaxLevel -> 0.369257
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseMinLevel -> 0.096560
	not: 	[derivative_decrease_right, row_1]:		derivDecreaseRight -> 1
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
			[integral, row_2]:		left -> 4
			[integral, row_2]:		maxLevel -> -4.747489
			[integral, row_2]:		minLevel -> -5.597122
			[integral, row_2]:		right -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseLeft -> 2
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMaxLevel -> 0.752016
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMinLevel -> 0.053496
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseRight -> 0
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.420200
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.114540
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseLeft -> 2
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMaxLevel -> 0.752016
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMinLevel -> 0.053496
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseRight -> 0
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseLeft -> 2
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMaxLevel -> 0.752016
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMinLevel -> 0.053496
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseMinLevel -> 0.047434
	not: 	[second_derivative_increase_right, row_1]:		secDerivIncreaseRight -> 2
			[integral, row_2]:		left -> 4
			[integral, row_2]:		maxLevel -> -4.747489
			[integral, row_2]:		minLevel -> -5.597122
			[integral, row_2]:		right -> 2
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseLeft -> 2
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMaxLevel -> 0.752016
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseMinLevel -> 0.053496
	not: 	[second_derivative_decrease_left, row_2]:		secDerivDecreaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.114540
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseLeft -> 1
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMaxLevel -> 0.339290
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseMinLevel -> 0.093563
	not: 	[decrease_left_elementary_condition, row_1]:		decreaseRight -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseLeft -> 0
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMaxLevel -> 0.671764
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseMinLevel -> 0.054117
	not: 	[second_derivative_decrease_right, row_1]:		secDerivDecreaseRight -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseLeft -> 2
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMaxLevel -> 0.842479
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseMinLevel -> 0.018204
	not: 	[second_derivative_increase_left, row_1]:		secDerivIncreaseRight -> 0
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.369072
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.114483
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.117537
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseLeft -> 1
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMaxLevel -> 0.420200
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseMinLevel -> 0.117537
	not: 	[derivative_decrease_left, row_1]:		derivDecreaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[volatility, row_1]:		left -> 4
	not: 	[volatility, row_1]:		maxLevel -> 0.411000
	not: 	[volatility, row_1]:		minLevel -> 0.003000
	not: 	[volatility, row_1]:		right -> 5
	not: 	[increase_left_elementary_condition, row_2]:		increaseLeft -> 1
	not: 	[increase_left_elementary_condition, row_2]:		increaseMaxLevel -> 0.360087
	not: 	[increase_left_elementary_condition, row_2]:		increaseMinLevel -> 0.120473
	not: 	[increase_left_elementary_condition, row_2]:		increaseRight -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseLeft -> 0
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMaxLevel -> 0.764208
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseMinLevel -> 0.030493
	not: 	[second_derivative_increase_right, row_2]:		secDerivIncreaseRight -> 2
	not: 	[increase_right_elementary_condition, row_2]:		increaseLeft -> 0
	not: 	[increase_right_elementary_condition, row_2]:		increaseMaxLevel -> 0.458927
	not: 	[increase_right_elementary_condition, row_2]:		increaseMinLevel -> 0.138444
	not: 	[increase_right_elementary_condition, row_2]:		increaseRight -> 1
